name: Stable
on: [push, pull_request]
jobs:
  macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-13, macos-14, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          MAKEFLAGS: -j3
        run: |
          cmake .
          make
          ./hello1
          sleep 1
          ./hello2
